Added bunch of api
Rolstenhouse/unofficial-apis pull request #23
Opened 2020-05-22 14:32 UTC by jzarca01

2020-05-22 17:31 UTC, Rolstenhouse requested changes
Do you mind alphabetizing and ordering the repos? Thanks! Cool to see how many unofficial APIs you've added.

2020-05-22 17:31 UTC, Rolstenhouse commented on README.md
> +[NobodySurf](https://github.com/jzarca01/node-nobodysurf) | An API for the video app NobodySurf | JavaScript | [![badge](https://img.shields.io/github/stars/jzarca01/node-nobodysurf.svg?style=social&
This doesn't look like the shields are resolving. Can you look into this?

2020-05-23 09:59 UTC, jzarca01 commented
Done ✅

2020-05-25 21:45 UTC, Rolstenhouse commented
Thanks!

2020-05-25 21:45 UTC, merged